In [24]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as bs
import requests as re

In [25]:
url='https://www.amazon.in/New-Apple-iPhone-12-128GB/product-reviews/B08L5TNJHG/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2'

In [26]:
page=re.get(url,headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36'})

In [27]:
page

<Response [200]>

In [28]:
page.content

b'\n\n\n\n<!doctype html><html class="a-no-js" data-19ax5a9jf="dingo">\n  <head>\n<script type=\'text/javascript\'>var ue_t0=ue_t0||+new Date();</script>\n<script type=\'text/javascript\'>\nwindow.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;\nif (window.ue_ihb === 1) {\n\nvar ue_csm = window,\n    ue_hob = +new Date();\n(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);\n\n\n    var ue_err_chan = \'jserr-rw\';\n(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+

In [29]:
soup1=bs(page.content,'html.parser')

In [30]:
soup1


<!DOCTYPE html>
<html class="a-no-js" data-19ax5a9jf="dingo">
<head>
<script type="text/javascript">var ue_t0=ue_t0||+new Date();</script>
<script type="text/javascript">
window.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;
if (window.ue_ihb === 1) {

var ue_csm = window,
    ue_hob = +new Date();
(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);


    var ue_err_chan = 'jserr-rw';
(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"

In [31]:
print(soup1.prettify())

<!DOCTYPE html>
<html class="a-no-js" data-19ax5a9jf="dingo">
 <head>
  <script type="text/javascript">
   var ue_t0=ue_t0||+new Date();
  </script>
  <script type="text/javascript">
   window.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;
if (window.ue_ihb === 1) {

var ue_csm = window,
    ue_hob = +new Date();
(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);


    var ue_err_chan = 'jserr-rw';
(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.l

In [32]:
names1=soup1.find_all('div',class_='a-profile-content')

In [33]:
cust_name1=[]
for i in range(0,len(names1)):
    cust_name1.append(names1[i].get_text())

In [34]:
cust_name1

[]

In [35]:
cust_name1.pop(0)

IndexError: pop from empty list

In [ ]:
cust_name1.pop(0)

In [ ]:
review_title1=soup1.find_all('a',class_='review-title')

In [ ]:
review_title1

In [ ]:
re_title1=[]
for i in range(0,len(review_title1)):
    re_title1.append(review_title1[i].get_text())
re_title1

In [ ]:
#list comprehension
re_title1[:]=[titles.lstrip('\n') for titles in re_title1]

In [ ]:
re_title1

In [ ]:
re_title1[:]=[titles.rstrip() for titles in re_title1]

In [ ]:
re_title1

In [ ]:
rating1=soup1.find_all('i',class_='review-rating')

In [ ]:
rating1

In [ ]:
ratings1=[]
for i in range(0,len(rating1)):
    ratings1.append(rating1[i].get_text())
ratings1

In [ ]:
ratings1.pop(0)

In [ ]:
ratings1.pop(0)

In [ ]:
ratings1[:]=[x.rstrip(' out of 5 stars') for x in ratings1]
ratings1

In [ ]:
comment1=soup1.find_all('span',{'data-hook':"review-body"})
comment1

In [ ]:
re_comments1=[]
for i in range(0,len(comment1)):
    re_comments1.append(comment1[i].get_text())
re_comments1

In [ ]:
re_comments1[:]=[x.lstrip('\n') for x in re_comments1]

In [ ]:
re_comments1[:]=[x.rstrip('\n') for x in re_comments1]

In [ ]:
re_comments1

In [ ]:
len(re_comments1)

In [ ]:
cust_name1
re_comments1
ratings1
re_title1

In [ ]:
data1=pd.DataFrame({'name':cust_name1,'titles':re_title1,'rating':ratings1,'comments':re_comments1})
data1

### Now i going to use for loop coz manualy i only get more than 10 user data. so using i can get user data from other pages

In [ ]:
# firstly i stored urls of next pages and stored in variable
URL=[]
for i in range(1,1200):
    url='https://www.amazon.in/New-Apple-iPhone-12-128GB/product-reviews/B08L5TNJHG/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber='
    URL.append(url+str(i))

# then i exctracted name,title,rating and comments from all those pages
cust_name=[]
re_title=[]
ratings=[]
re_comments=[]

for i in URL:    
    page=re.get(i)
    
    soup=bs(page.content,'html.parser')
    
    names=soup.find_all('div',class_='a-profile-content')
    
    for i in range(0,len(names)):
        cust_name.append(names[i].get_text())
    
    review_title=soup.find_all('a',class_='review-title')
    
    for i in range(0,len(review_title)):
        re_title.append(review_title[i].get_text())

    #list comprehension to remove '\n' unwanted charactar
    re_title[:]=[titles.lstrip('\n') for titles in re_title]
    re_title[:]=[titles.rstrip('\n') for titles in re_title]
    
    rating=soup.find_all('i',class_='review-rating')
    
    for i in range(0,len(rating)):
        ratings.append(rating[i].get_text())
    ratings
    
    ratings[:]=[x.rstrip(' out of 5 stars') for x in ratings]
    ratings
    
    comment=soup.find_all('span',{'data-hook':"review-body"})
    comment
    
    for i in range(0,len(comment)):
        re_comments.append(comment[i].get_text())
    re_comments
    
    re_comments[:]=[x.lstrip('\n') for x in re_comments]
    re_comments[:]=[x.rstrip('\n') for x in re_comments]



In [ ]:
if len(re_comments)<len(ratings):
    c=len(ratings)-len(re_comments)
    c=int(c)
    for i in range(0,c):
        ratings.pop(i)
        cust_name.pop(i)
        if len(re_comments)==len(ratings):
            print('now the length is equal of both variables')

In [ ]:
len(re_comments)

In [ ]:
len(ratings)

In [ ]:
len(re_title)

In [ ]:
# i tried to convert into dataframe but some of the values from colunms was missing so i cant create the dataframe
#data=pd.DataFrame({'name':cust_name,'rating':ratings,'titles':re_title,'comments':re_comments,})

In [ ]:
data=pd.DataFrame({'name':cust_name,'titles':re_title,'rating':ratings,'comments':re_comments})
data

In [ ]:
data.to_csv(r'Iphone-12_Review.csv',index=True)

###  Now we are doing emotion mining on the dataset

In [582]:
# we imported saved csv file so we can check is it having any issue while importing or not
data=pd.read_csv('Iphone-12_Review_main.csv',index_col=0)

In [583]:
data.head()

name                                             titles  \
0          Yaswanth S.                 An overall good premium experience   
1          Navish Paik                                  Excellent product   
2         Mantu  kumar               In the era of 14 this is still beast   
3  Yogesh Kumar Sharma                      mujhe acha laga istmal kar ke   
4      Swapnil S Joshi  iphone 12 is good for normal use but don’t exp...   

   rating                                           comments  
0     3.0  SUMMERY: As a first time iPhone user, I would ...  
1     4.0  Satisfied with the quality and performance but...  
2     4.0  Using for few months, no heating issue, but ni...  
3     4.0                           In 2022 best iPhone ever  
4     4.0  Whereas brand is apple, you can expect standar...

In [584]:
data.duplicated().sum()

14

In [585]:
data.drop_duplicates(inplace=True)

In [586]:
data.isna().sum()

name          0
titles        3
rating        0
comments    100
dtype: int64

In [587]:
data.dropna(inplace=True)

In [588]:
data.reset_index(inplace=True)

In [589]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920 entries, 0 to 1919
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   index     1920 non-null   int64  
 1   name      1920 non-null   object 
 2   titles    1920 non-null   object 
 3   rating    1920 non-null   float64
 4   comments  1920 non-null   object 
dtypes: float64(1), int64(1), object(3)
memory usage: 75.1+ KB


In [590]:
data.isna().sum()

index       0
name        0
titles      0
rating      0
comments    0
dtype: int64

In [591]:
data.duplicated().sum()

0

In [592]:
data1=data.loc[:,['comments']]

In [593]:
data1

comments
0     SUMMERY: As a first time iPhone user, I would ...
1     Satisfied with the quality and performance but...
2     Using for few months, no heating issue, but ni...
3                              In 2022 best iPhone ever
4     Whereas brand is apple, you can expect standar...
...                                                 ...
1915      Upgraded from 7+. Amazing product. Loving it.
1916          No need to comment because this is Apple.
1917  Upgraded from iPhone x after over 3 years. I d...
1918  Just great, feel awesome to unbox all good at ...
1919                                   Good performance

[1920 rows x 1 columns]

In [594]:
# as you can there are still number there
import re

In [595]:
def remove_pattern(text,pattern):
    x=re.findall(pattern,str(text))
    for i in x:
        text=re.sub(i,'',str(text))
    return text

In [596]:
data1['cleaned']=data1['comments'].apply(lambda x: remove_pattern(x,'[0-9]*'))
data1

comments  \
0     SUMMERY: As a first time iPhone user, I would ...   
1     Satisfied with the quality and performance but...   
2     Using for few months, no heating issue, but ni...   
3                              In 2022 best iPhone ever   
4     Whereas brand is apple, you can expect standar...   
...                                                 ...   
1915      Upgraded from 7+. Amazing product. Loving it.   
1916          No need to comment because this is Apple.   
1917  Upgraded from iPhone x after over 3 years. I d...   
1918  Just great, feel awesome to unbox all good at ...   
1919                                   Good performance   

                                                cleaned  
0     SUMMERY: As a first time iPhone user, I would ...  
1     Satisfied with the quality and performance but...  
2     Using for few months, no heating issue, but ni...  
3                                  In  best iPhone ever  
4     Whereas brand is apple, you can expect standar...  
...                                                 ...  
1915       Upgraded from +. Amazing product. Loving it.  
1916          No need to comment because this is Apple.  
1917  Upgraded from iPhone x after over  years. I do...  
1918  Just great, feel awesome to unbox all good at ...  
1919                                   Good performance  

[1920 rows x 2 columns]

In [597]:
from nltk.corpus import stopwords

In [598]:
# i didnt removed punctuations 
stop_words=list(stopwords.words('english'))

In [599]:
from nltk import word_tokenize

In [600]:
data1['tokenized']=[word_tokenize(x) for x in data1['cleaned']]
data1

comments  \
0     SUMMERY: As a first time iPhone user, I would ...   
1     Satisfied with the quality and performance but...   
2     Using for few months, no heating issue, but ni...   
3                              In 2022 best iPhone ever   
4     Whereas brand is apple, you can expect standar...   
...                                                 ...   
1915      Upgraded from 7+. Amazing product. Loving it.   
1916          No need to comment because this is Apple.   
1917  Upgraded from iPhone x after over 3 years. I d...   
1918  Just great, feel awesome to unbox all good at ...   
1919                                   Good performance   

                                                cleaned  \
0     SUMMERY: As a first time iPhone user, I would ...   
1     Satisfied with the quality and performance but...   
2     Using for few months, no heating issue, but ni...   
3                                  In  best iPhone ever   
4     Whereas brand is apple, you can expect standar...   
...                                                 ...   
1915       Upgraded from +. Amazing product. Loving it.   
1916          No need to comment because this is Apple.   
1917  Upgraded from iPhone x after over  years. I do...   
1918  Just great, feel awesome to unbox all good at ...   
1919                                   Good performance   

                                              tokenized  
0     [SUMMERY, :, As, a, first, time, iPhone, user,...  
1     [Satisfied, with, the, quality, and, performan...  
2     [Using, for, few, months, ,, no, heating, issu...  
3                              [In, best, iPhone, ever]  
4     [Whereas, brand, is, apple, ,, you, can, expec...  
...                                                 ...  
1915  [Upgraded, from, +, ., Amazing, product, ., Lo...  
1916  [No, need, to, comment, because, this, is, App...  
1917  [Upgraded, from, iPhone, x, after, over, years...  
1918  [Just, great, ,, feel, awesome, to, unbox, all...  
1919                                [Good, performance]  

[1920 rows x 3 columns]

In [601]:
data1['tokenized']=data1['tokenized'].apply(lambda x: [word for word in x if word not in stop_words])

In [602]:
data1.head()

comments  \
0  SUMMERY: As a first time iPhone user, I would ...   
1  Satisfied with the quality and performance but...   
2  Using for few months, no heating issue, but ni...   
3                           In 2022 best iPhone ever   
4  Whereas brand is apple, you can expect standar...   

                                             cleaned  \
0  SUMMERY: As a first time iPhone user, I would ...   
1  Satisfied with the quality and performance but...   
2  Using for few months, no heating issue, but ni...   
3                               In  best iPhone ever   
4  Whereas brand is apple, you can expect standar...   

                                           tokenized  
0  [SUMMERY, :, As, first, time, iPhone, user, ,,...  
1  [Satisfied, quality, performance, 's, battery,...  
2  [Using, months, ,, heating, issue, ,, night, c...  
3                           [In, best, iPhone, ever]  
4  [Whereas, brand, apple, ,, expect, standard, h...

In [603]:
data1

comments  \
0     SUMMERY: As a first time iPhone user, I would ...   
1     Satisfied with the quality and performance but...   
2     Using for few months, no heating issue, but ni...   
3                              In 2022 best iPhone ever   
4     Whereas brand is apple, you can expect standar...   
...                                                 ...   
1915      Upgraded from 7+. Amazing product. Loving it.   
1916          No need to comment because this is Apple.   
1917  Upgraded from iPhone x after over 3 years. I d...   
1918  Just great, feel awesome to unbox all good at ...   
1919                                   Good performance   

                                                cleaned  \
0     SUMMERY: As a first time iPhone user, I would ...   
1     Satisfied with the quality and performance but...   
2     Using for few months, no heating issue, but ni...   
3                                  In  best iPhone ever   
4     Whereas brand is apple, you can expect standar...   
...                                                 ...   
1915       Upgraded from +. Amazing product. Loving it.   
1916          No need to comment because this is Apple.   
1917  Upgraded from iPhone x after over  years. I do...   
1918  Just great, feel awesome to unbox all good at ...   
1919                                   Good performance   

                                              tokenized  
0     [SUMMERY, :, As, first, time, iPhone, user, ,,...  
1     [Satisfied, quality, performance, 's, battery,...  
2     [Using, months, ,, heating, issue, ,, night, c...  
3                              [In, best, iPhone, ever]  
4     [Whereas, brand, apple, ,, expect, standard, h...  
...                                                 ...  
1915   [Upgraded, +, ., Amazing, product, ., Loving, .]  
1916                      [No, need, comment, Apple, .]  
1917  [Upgraded, iPhone, x, years, ., I, ’, see, maj...  
1918  [Just, great, ,, feel, awesome, unbox, good, f...  
1919                                [Good, performance]  

[1920 rows x 3 columns]

In [604]:
from nltk import PorterStemmer

In [605]:
stemm=PorterStemmer()

In [606]:
data1['tokenized']=data1['tokenized'].apply(lambda x:[stemm.stem(i) for i in x])

In [607]:
data1.head()

comments  \
0  SUMMERY: As a first time iPhone user, I would ...   
1  Satisfied with the quality and performance but...   
2  Using for few months, no heating issue, but ni...   
3                           In 2022 best iPhone ever   
4  Whereas brand is apple, you can expect standar...   

                                             cleaned  \
0  SUMMERY: As a first time iPhone user, I would ...   
1  Satisfied with the quality and performance but...   
2  Using for few months, no heating issue, but ni...   
3                               In  best iPhone ever   
4  Whereas brand is apple, you can expect standar...   

                                           tokenized  
0  [summeri, :, as, first, time, iphon, user, ,, ...  
1  [satisfi, qualiti, perform, 's, batteri, drain...  
2  [use, month, ,, heat, issu, ,, night, camera, ...  
3                            [in, best, iphon, ever]  
4  [wherea, brand, appl, ,, expect, standard, han...

In [608]:
data1['tokenized']=data1['tokenized'].apply(lambda x:' '.join(x))

In [609]:
data1

comments  \
0     SUMMERY: As a first time iPhone user, I would ...   
1     Satisfied with the quality and performance but...   
2     Using for few months, no heating issue, but ni...   
3                              In 2022 best iPhone ever   
4     Whereas brand is apple, you can expect standar...   
...                                                 ...   
1915      Upgraded from 7+. Amazing product. Loving it.   
1916          No need to comment because this is Apple.   
1917  Upgraded from iPhone x after over 3 years. I d...   
1918  Just great, feel awesome to unbox all good at ...   
1919                                   Good performance   

                                                cleaned  \
0     SUMMERY: As a first time iPhone user, I would ...   
1     Satisfied with the quality and performance but...   
2     Using for few months, no heating issue, but ni...   
3                                  In  best iPhone ever   
4     Whereas brand is apple, you can expect standar...   
...                                                 ...   
1915       Upgraded from +. Amazing product. Loving it.   
1916          No need to comment because this is Apple.   
1917  Upgraded from iPhone x after over  years. I do...   
1918  Just great, feel awesome to unbox all good at ...   
1919                                   Good performance   

                                              tokenized  
0     summeri : as first time iphon user , i would s...  
1     satisfi qualiti perform 's batteri drain quick...  
2          use month , heat issu , night camera worst .  
3                                    in best iphon ever  
4     wherea brand appl , expect standard handset . ...  
...                                                 ...  
1915                   upgrad + . amaz product . love .  
1916                             no need comment appl .  
1917  upgrad iphon x year . i ’ see major chang upgr...  
1918  just great , feel awesom unbox good first conf...  
1919                                       good perform  

[1920 rows x 3 columns]

In [610]:
data2=data1.loc[:,['tokenized']]

In [611]:
data2

tokenized
0     summeri : as first time iphon user , i would s...
1     satisfi qualiti perform 's batteri drain quick...
2          use month , heat issu , night camera worst .
3                                    in best iphon ever
4     wherea brand appl , expect standard handset . ...
...                                                 ...
1915                   upgrad + . amaz product . love .
1916                             no need comment appl .
1917  upgrad iphon x year . i ’ see major chang upgr...
1918  just great , feel awesom unbox good first conf...
1919                                       good perform

[1920 rows x 1 columns]

In [612]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [613]:
analyser=SentimentIntensityAnalyzer()

In [614]:
def sentiment_score(text):
    analyser=SentimentIntensityAnalyzer()
    senti_dict=analyser.polarity_scores(text)
    senti=[]
    for i in senti_dict:
        if senti_dict['compound']>0.5:
            senti.append(1)
        elif senti_dict['compound']<=-0.5:
            senti.append(2)
        else :
            senti.append(0)
    
    return senti[0]

In [615]:
data3=data2

In [616]:
data3

tokenized
0     summeri : as first time iphon user , i would s...
1     satisfi qualiti perform 's batteri drain quick...
2          use month , heat issu , night camera worst .
3                                    in best iphon ever
4     wherea brand appl , expect standard handset . ...
...                                                 ...
1915                   upgrad + . amaz product . love .
1916                             no need comment appl .
1917  upgrad iphon x year . i ’ see major chang upgr...
1918  just great , feel awesom unbox good first conf...
1919                                       good perform

[1920 rows x 1 columns]

In [617]:
data3['target']=data3['tokenized'].apply(lambda x: sentiment_score(x))

In [618]:
data3

tokenized  target
0     summeri : as first time iphon user , i would s...       1
1     satisfi qualiti perform 's batteri drain quick...       0
2          use month , heat issu , night camera worst .       2
3                                    in best iphon ever       1
4     wherea brand appl , expect standard handset . ...       1
...                                                 ...     ...
1915                   upgrad + . amaz product . love .       1
1916                             no need comment appl .       0
1917  upgrad iphon x year . i ’ see major chang upgr...       1
1918  just great , feel awesom unbox good first conf...       1
1919                                       good perform       0

[1920 rows x 2 columns]

In [619]:
data3[data3['target']==2]

tokenized  target
2          use month , heat issu , night camera worst .       2
209   hello , i write review - day usag , iphon beas...       2
239   if u cn compromis wit batri den go fr .. el dn...       2
263   the media could load . deliveri amazon amaz . ...       2
275   i ’ write review later , short , hardcor andro...       2
...                                                 ...     ...
1831  in descript iphon . inch display , actual rece...       2
1834  worst ever phone low camera batteri life low q...       2
1839  wast money display qualiti also poor batteri w...       2
1876                         i amma die hard iphon user       2
1888  i disappoint see charger earphon . it ’ sad ap...       2

[79 rows x 2 columns]

In [620]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920 entries, 0 to 1919
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   tokenized  1920 non-null   object
 1   target     1920 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 30.1+ KB


In [621]:
data3['target'].value_counts()

0    1064
1     777
2      79
Name: target, dtype: int64

###  now we using CountVector

In [622]:
from sklearn.feature_extraction.text import CountVectorizer

In [623]:
cv=CountVectorizer()
cv_text=cv.fit_transform(data3['tokenized'])

### Logistic Regression

In [624]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from imblearn.over_sampling import SMOTE

In [625]:
lr=LogisticRegression()
sm=SMOTE()

In [626]:
x=cv_text
y=data3['target']

In [627]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=42)

In [628]:
x_train,y_train=sm.fit_resample(x_train,y_train)

In [629]:
y_train.value_counts()

1    713
0    713
2    713
Name: target, dtype: int64

In [630]:
model_log=lr.fit(x_train,y_train)

In [631]:
print('accuracy :',model_log.score(x_train,y_train)*100)

accuracy : 95.27816736792893


In [632]:
print('accuracy :',model_log.score(x_test,y_test)*100)

accuracy : 74.76340694006309


In [633]:
y_pred=model_log.predict(x_test)

In [634]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.77      0.78       351
           1       0.87      0.74      0.80       259
           2       0.17      0.50      0.26        24

    accuracy                           0.75       634
   macro avg       0.61      0.67      0.61       634
weighted avg       0.80      0.75      0.77       634



In [635]:
confusion_matrix(y_test,y_pred)

array([[271,  27,  53],
       [ 64, 191,   4],
       [ 10,   2,  12]], dtype=int64)

### Naive Bayes

In [636]:
from sklearn.naive_bayes import MultinomialNB

In [637]:
nb=MultinomialNB()
model_2=nb.fit(x_train,y_train)

In [638]:
print('accuracy :',model_2.score(x_train,y_train)*100)

accuracy : 77.23235156615242


In [639]:
print('accuracy :',model_2.score(x_test,y_test)*100)

accuracy : 64.35331230283911


In [640]:
y_pred=model_2.predict(x_test)

In [641]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.50      0.62       351
           1       0.59      0.87      0.70       259
           2       0.22      0.33      0.26        24

    accuracy                           0.64       634
   macro avg       0.54      0.57      0.53       634
weighted avg       0.70      0.64      0.64       634



In [642]:
confusion_matrix(y_test,y_pred)

array([[174, 149,  28],
       [ 32, 226,   1],
       [  7,   9,   8]], dtype=int64)

### Decision Tree

In [643]:
from sklearn.tree import DecisionTreeClassifier

In [644]:
dt=DecisionTreeClassifier()
model_3=dt.fit(x_train,y_train)

In [645]:
print('accuracy :',model_3.score(x_train,y_train)*100)

accuracy : 97.38195418419822


In [646]:
print('accuracy :',model_3.score(x_test,y_test)*100)

accuracy : 75.39432176656152


In [647]:
y_pred=model_3.predict(x_test)

In [648]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.74      0.78       351
           1       0.84      0.80      0.82       259
           2       0.16      0.50      0.25        24

    accuracy                           0.75       634
   macro avg       0.61      0.68      0.61       634
weighted avg       0.81      0.75      0.77       634



In [649]:
confusion_matrix(y_test,y_pred)

array([[260,  35,  56],
       [ 48, 206,   5],
       [  8,   4,  12]], dtype=int64)

## XGBoost

In [650]:
from xgboost import XGBClassifier

In [651]:
xgb=XGBClassifier(n_estimators=150,max_depth=5)

In [652]:
xgb_model=xgb.fit(x_train,y_train)
xgb_model.score(x_train,y_train)

0.9915848527349228

In [653]:
xgb_model.score(x_test,y_test)

0.8470031545741324

In [654]:
y_pred=xgb_model.predict(x_test)

In [655]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.91      0.87       351
           1       0.88      0.79      0.84       259
           2       0.58      0.46      0.51        24

    accuracy                           0.85       634
   macro avg       0.77      0.72      0.74       634
weighted avg       0.85      0.85      0.84       634



In [656]:
confusion_matrix(y_test,y_pred)

array([[321,  25,   5],
       [ 51, 205,   3],
       [ 11,   2,  11]], dtype=int64)

### Now we are using TF-IDF

In [657]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [658]:
tf=TfidfVectorizer()
tf_text=tf.fit_transform(data3['tokenized'])

In [659]:
x=tf_text
y=data3['target']

In [660]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=42)
x_train,y_train=sm.fit_resample(x_train,y_train)
y_train.value_counts()

1    713
0    713
2    713
Name: target, dtype: int64

In [661]:
confusion_matrix(y_test,y_pred)

array([[321,  25,   5],
       [ 51, 205,   3],
       [ 11,   2,  11]], dtype=int64)

### Logistic regression

In [662]:
lr=LogisticRegression()
tf_model_1=lr.fit(x_train,y_train)

In [663]:
print('accuracy :',tf_model_1.score(x_train,y_train)*100)

accuracy : 93.78214118747078


In [664]:
print('accuracy :',tf_model_1.score(x_test,y_test)*100)

accuracy : 80.4416403785489


In [665]:
y_pred=tf_model_1.predict(x_test)

In [666]:
print(classification_report(y_test,y_pred)) #80

              precision    recall  f1-score   support

           0       0.81      0.86      0.83       351
           1       0.81      0.77      0.79       259
           2       0.59      0.42      0.49        24

    accuracy                           0.80       634
   macro avg       0.74      0.68      0.70       634
weighted avg       0.80      0.80      0.80       634



In [667]:
confusion_matrix(y_test,y_pred)

array([[301,  44,   6],
       [ 59, 199,   1],
       [ 11,   3,  10]], dtype=int64)

## Random Forest

In [668]:
from sklearn.ensemble import RandomForestClassifier

In [669]:
rc=RandomForestClassifier(n_estimators=200)

In [670]:
rc_model=rc.fit(x_train,y_train)
rc_model.score(x_train,y_train)

0.9962599345488546

In [671]:
rc_model.score(x_test,y_test)

0.831230283911672

In [672]:
y_pred=rc_model.predict(x_test)

In [673]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87       351
           1       0.85      0.79      0.82       259
           2       0.50      0.17      0.25        24

    accuracy                           0.83       634
   macro avg       0.73      0.62      0.64       634
weighted avg       0.82      0.83      0.82       634



In [674]:
y_test.value_counts()

0    351
1    259
2     24
Name: target, dtype: int64

In [675]:
confusion_matrix(y_test,y_pred)

array([[319,  31,   1],
       [ 52, 204,   3],
       [ 14,   6,   4]], dtype=int64)

###  Naive bayes

In [676]:
tf_model_2=nb.fit(x_train,y_train)

In [677]:
print('accuracy :',tf_model_2.score(x_train,y_train)*100)

accuracy : 87.84478728377746


In [678]:
print('accuracy :',tf_model_2.score(x_test,y_test)*100)

accuracy : 65.14195583596214


In [679]:
y_pred=tf_model_2.predict(x_test)

In [680]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.54      0.65       351
           1       0.65      0.81      0.72       259
           2       0.16      0.58      0.26        24

    accuracy                           0.65       634
   macro avg       0.55      0.64      0.54       634
weighted avg       0.73      0.65      0.67       634



In [681]:
confusion_matrix(y_test,y_pred)

array([[188, 106,  57],
       [ 34, 211,  14],
       [  3,   7,  14]], dtype=int64)

### Decision Tree

In [682]:
dt=DecisionTreeClassifier()
tf_model_3=dt.fit(x_train,y_train)
print('accuracy :',tf_model_3.score(x_train,y_train)*100)

accuracy : 99.62599345488546


In [683]:
print('accuracy :',tf_model_3.score(x_test,y_test)*100)

accuracy : 79.49526813880126


In [684]:
y_pred=tf_model_3.predict(x_test)

In [685]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83       351
           1       0.79      0.77      0.78       259
           2       0.47      0.58      0.52        24

    accuracy                           0.79       634
   macro avg       0.69      0.73      0.71       634
weighted avg       0.80      0.79      0.80       634



In [686]:
confusion_matrix(y_test,y_pred)

array([[290,  51,  10],
       [ 53, 200,   6],
       [  8,   2,  14]], dtype=int64)

## XGBoost

In [687]:
from xgboost import XGBClassifier

In [708]:
xgb=XGBClassifier(n_estimators=200,max_depth=10)#80,5

In [709]:
tf_xgb_model=xgb.fit(x_train,y_train)
xgb_model.score(x_train,y_train)

0.9934548854604955

In [710]:
tf_xgb_model.score(x_test,y_test)

0.8391167192429022

In [711]:
y_pred=tf_xgb_model.predict(x_test)

In [712]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87       351
           1       0.87      0.78      0.82       259
           2       0.62      0.54      0.58        24

    accuracy                           0.84       634
   macro avg       0.77      0.74      0.76       634
weighted avg       0.84      0.84      0.84       634



In [713]:
confusion_matrix(y_test,y_pred)

array([[318,  28,   5],
       [ 55, 201,   3],
       [  9,   2,  13]], dtype=int64)

In [701]:
import joblib as jb

In [714]:
jb.dump(tf_xgb_model,'xgb_model.pkl')

['xgb_model.pkl']