In [74]:
import pandas as pd
import numpy as np

In [75]:
data=pd.read_csv('Zoo.csv')

In [76]:
data.head() # all are the unique machne get confussed

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   type  
0     1  
1     1  
2     4  
3     1  
4     1

In [77]:
data.drop('animal name',axis=1,inplace=True)

In [78]:
data.isnull().sum()

hair        0
feathers    0
eggs        0
milk        0
airborne    0
aquatic     0
predator    0
toothed     0
backbone    0
breathes    0
venomous    0
fins        0
legs        0
tail        0
domestic    0
catsize     0
type        0
dtype: int64

In [79]:
data['hair'].value_counts()

0    58
1    43
Name: hair, dtype: int64

In [80]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   hair      101 non-null    int64
 1   feathers  101 non-null    int64
 2   eggs      101 non-null    int64
 3   milk      101 non-null    int64
 4   airborne  101 non-null    int64
 5   aquatic   101 non-null    int64
 6   predator  101 non-null    int64
 7   toothed   101 non-null    int64
 8   backbone  101 non-null    int64
 9   breathes  101 non-null    int64
 10  venomous  101 non-null    int64
 11  fins      101 non-null    int64
 12  legs      101 non-null    int64
 13  tail      101 non-null    int64
 14  domestic  101 non-null    int64
 15  catsize   101 non-null    int64
 16  type      101 non-null    int64
dtypes: int64(17)
memory usage: 13.5 KB


In [81]:
data.duplicated().sum()

42

In [82]:
data.drop_duplicates(inplace=True)

In [83]:
data.reset_index(inplace=True)

In [84]:
x=data.iloc[:,2:]
y=data.iloc[:,[1]]

In [85]:
sm=SMOTE()

In [86]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=42)
x_train,y_train=sm.fit_resample(x_train,y_train)

In [87]:
y_train.value_counts()

hair
0       26
1       26
dtype: int64

In [88]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [89]:
knn=KNeighborsClassifier(n_neighbors=1)
k_f=KFold(n_splits=10,shuffle=True)
g_v=cross_val_score(knn,x_train,y_train,cv=k_f)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples

In [90]:
print(g_v.mean())

0.8833333333333334


In [91]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

In [92]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=42)
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=.30,random_state=42)

In [94]:
x_train,y_train=sm.fit_resample(x_train,y_train)

In [95]:
y_train.value_counts()

hair
0       17
1       17
dtype: int64

In [96]:
y_val.value_counts()

hair
0       9
1       3
dtype: int64

In [97]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

In [98]:
knn=KNeighborsClassifier()
k_f=KFold(n_splits=5,shuffle=True)
params={'n_neighbors':range(1,10)}
g_v=GridSearchCV(knn,param_grid=params,cv=k_f)
model=g_v.fit(x_train,y_train)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples

C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples

In [99]:
model.best_params_

{'n_neighbors': 1}

In [100]:
model.best_score_

0.9142857142857143

In [102]:
model.score(x_val,y_val)

0.9166666666666666

In [103]:
model.score(x_test,y_test)

0.9

In [104]:
y_val=model.predict(x_val)

In [105]:
y_pred=model.predict(x_test)

In [106]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1],
      dtype=int64)

In [107]:
y_val

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [108]:
from sklearn.metrics import classification_report

In [109]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       1.00      0.80      0.89        10

    accuracy                           0.90        20
   macro avg       0.92      0.90      0.90        20
weighted avg       0.92      0.90      0.90        20



In [111]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1],
      dtype=int64)